backtraces_path = "/home/patweatharva/.local/share/neovide"
fork = false
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
neovim-bin = "/opt/nvim/nvim"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false 
wsl = false

[font]
size = 12

# Main font set to a heavier weight for increased boldness
[[font.normal]]
family = "0xProto Nerd Font Mono"
style = "SemiBold"     # Try "Bold" for maximum boldness, or "SemiBold" for slightly less

[[font.bold]]
family = "0xProto Nerd Font Mono"
style = "Bold"

[[font.italic]]
family = "0xProto Nerd Font Mono"
style = "Italic"

[[font.bold_italic]]
family = "0xProto Nerd Font Mono"
style = "Bold Italic"

#[font.features]
#"0xProto Nerd Font Mono" = [ "+ss01", "+ss02" ]  # Enable font features if desired

[box-drawing]
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]

